name: fittrack
description: "A new Flutter project."

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.2

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  intl_utils: ^2.4.0
  flutter_lints: ^5.0.0  # ici dans dev_dependencies

flutter_intl:
  enabled: true
  arb_dir: lib/src/localization  # Répertoire où se trouvent tes fichiers .arb
  template_arbs:
    - lib/src/localization/app_en.arb  # Fichier de base

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
