name: fittrack
description: "A new Flutter project."

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.2

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  shared_preferences: ^2.0.15
  intl: ^0.19.0
  country_flags: ^3.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  intl_utils: ^2.4.0
  flutter_lints: ^5.0.0

flutter_intl:
  enabled: true
  arb_dir: lib/src/localization  # Répertoire où se trouvent tes fichiers .arb
  template_arbs:
    - lib/src/localization/intl_en.arb  # Fichier de base
  output_dir: lib/src/generated  # Dossier où seront générés les fichiers Dart

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/

# Localization settings moved here
flutter_localizations:
  delegates:
    - flutter_localizations:
        sdk: flutter
    - app_localizations:
        path: lib/src/generated  # Chemin vers les fichiers générés
  supportedLocales:
    - en
    - fr  # Ajout de la langue française ici
